config/routes.rb
# -*- coding: utf-8 -*-
Rails.application.routes.draw do

  root to: 'products#index'

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout"},
    controllers: { omniauth_callbacks: "omniauth_callbacks" }

  get  '/products/',    to: 'products#index'
  get  '/products/new', to: 'products#new'
  get  '/products/:id', to: 'products#destroy'
  post '/products/',    to: 'products#create'  
end

app/models/product.rb
# -*- coding: utf-8 -*-
# == Schema Information
#
# Table name: products
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  image      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_products_on_user_id  (user_id)
#

class Product < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :user
  scope :mine, ->(user_id) {where("user_id = ?",user_id)}
end

app/models/user.rb
# -*- coding: utf-8 -*-
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime
#  updated_at             :datetime
#  username               :string
#  provider               :string
#  uid                    :string
#  image                  :string
#  failed_attempts        :integer          default(0), not null
#  locked_at              :datetime
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_username              (username) UNIQUE
#

class User < ActiveRecord::Base
  has_many :products, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :lockable,
         :omniauthable, omniauth_providers: [:twitter]

  validates :username, presence: true, uniqueness: true


  def self.from_omniauth(auth)
    # providerとuidでUserレコードを取得する
    # 存在しない場合は、ブロック内のコードを実行して作成する
    #where(auth.slice(:provider, :uid)).first_or_create do |user|
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      # auth.provider には "twitter"、
      # auth.uidには twitterアカウントに基づいた個別のIDが入っている
      # first_or_createメソッドが自動でproviderとuidを設定してくれるので、
      # ここでは設定は必要ない
      user.username = auth.info.nickname # twitterで利用している名前が入る
      user.email = auth.info.email # twitterの場合入らない
      user.image = auth.info.image
    end
  end
  
  # Devise の RegistrationsController はリソースを生成する前に self.new_sith_session を呼ぶ
  # つまり、self.new_with_sessionを実装することで、サインアップ前のuserオブジェクトを初期化する
  # ときに session からデータをコピーすることができます。
  # OmniauthCallbacksControllerでsessionに値を設定したので、それをuserオブジェクトにコピーします。
  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  # providerがある場合（Twitter経由で認証した）は、passwordは要求しないようにする。
  def password_required?
    super && provider.blank?
  end

  # プロフィールを変更するときによばれる
  def update_with_password(params, *options)
    # パスワードが空の場合、パスワードがなくても更新できる
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end
  
end

app/controllers/application_controller.rb
# -*- coding: utf-8 -*-
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # deviceのコントローラーのときに、下記のメソッドを呼ぶ
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    # sign_upのときに、usernameも許可する
    devise_parameter_sanitizer.for(:sign_up) << :username
    #  account_updateのときに、usernameも許可する
    devise_parameter_sanitizer.for(:account_update) << :username
  end
end

app/controllers/omniauth_callbacks_controller.rb
# -*- coding: utf-8 -*-
class OmniauthCallbacksController < ApplicationController

  def all
    # profiderとuidでuserレコードを検索。存在しなければ、新たに作成する
    user = User.from_omniauth(request.env["omniauth.auth"])
    # userレコードが既に保存されているか
    if user.persisted?
      # ログインに成功
      flash.notice = "ログインしました!!"
      sign_in_and_redirect user
    else
      # ログインに失敗し、サインイン画面に遷移
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end

  # alias_methodはクラスやモジュールのメソッドに別名をつけます
  # 実態がallメソッドのtwitterメソッドを定義しています
  # こうすることで、様々なメソッド名で同じ処理を実装することができます。
  # OAuthの処理はほとんど同じためこのようにしています。
  # 例えば、Facebookに対応する場合、alias_method :facebook, :allだけですみます
  alias_method :twitter, :all
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: [:destroy]

  # GET /products
  def index
    @products = Product.mine(current_user.id)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # POST /products
  # POST /products.json
  def create
    files = params[:files]
    files.each do |image|
      @product = Product.new({ image: image, user_id: current_user.id })
      @product.save
    end

    respond_to do |format|
      format.html { render :new }
    end
  end

  # DELETE /products/1
  def destroy
    if @product.user_id == current_user.id
      @product.destroy
    end

    respond_to do |format|
      format.html { redirect_to action: 'index' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:image, :image_cache, :remove_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |errmsg|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{errmsg}
      </div>
      EOF
    end
    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StudyUploader</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name -%> <%= action_name -%>">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">StudyUploader</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <% if user_signed_in? %>
                        <li><%= link_to 'アップロード', products_new_path %></li>
                        <li><%= link_to '画像一覧', products_path %></li>
                        <li><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
                        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
                    <% else %>
                        <li><%= link_to "サインイン", new_user_registration_path %></li>
                        <li><%= link_to "ログイン", new_user_session_path %></li>
                        <li><%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %></li>
                    <% end %>
                </ul>
                <% if user_signed_in? %>
                    <% if current_user.image %>
                        <ul class="nav navbar-nav navbar-right">
                            <div class="row">
                                <div class="col-xs-6 col-md-6">
                                    <a href="#" class="thumbnail">
                                        <img src="<%= current_user.image %>" />
                                    </a>
                                </div>
                            </div>
                        </ul>
                    <% end %>
                <% end %>
            </div><!--/.nav-collapse -->
        </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
</body>
</html>

app/views/products/index.html.erb
<style>
.thumbnail img {
    max-height: 90px;
}
</style>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>画像一覧</h2>
        </div>

        <div class="col-md-12" style="margin-top:20px; margin-bottom:20px;">
        <% @products.each do |product| %>
            <div class="col-md-2">
                <a href="#" class="thumbnail" data-toggle="modal" data-target="#myModal" data-url="<%= product.image %>" data-id="<%= product.id %>">
                    <img src="<%= product.image.thumb %>">
                </a>
            </div>
        <% end %>
        </div>
    </div>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body" style="text-align:center;">
                <img id="myModalImage" width="80%"/>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger" id="myModalDelete">Delete image</button>
            </div>
        </div>
    </div>
</div>
<script>
$('#myModal').on('show.bs.modal',function(e){
    thumbnail = e.relatedTarget;
    $("#myModalImage").attr("src",thumbnail.dataset.url);

    $("#myModalDelete").click(function(){
        location.href = "/products/" + thumbnail.dataset.id;
        return false;
    });
})
</script>

app/views/products/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>アップロード</h2>
        </div>
        <div class="col-md-12" style="margin-top:20px; margin-bottom:20px;">
            <div id="drag-area">
                <p>アップロードしたいファイルを、ここにドロップ＆ドロップ</p>
                <div class="btn-group">
                    <input type="file" multiple>
                    <button id="btn">ファイルを選択</button>
                </div>
            </div>
            <output id="list"></output>
        </div>
    </div>
</div>
<script>
 $(function(){
     /*================================================
        ファイルをドロップした時の処理
     =================================================*/
     $('#drag-area').bind('drop', function(e){
         e.preventDefault(); // デフォルトの挙動を停止

         var files = e.originalEvent.dataTransfer.files;
         handleFileSelect(files);

     }).bind('dragenter', function(){
         return false; // デフォルトの挙動を停止
     }).bind('dragover', function(){
         return false; // デフォルトの挙動を停止
     });

     /*================================================
        ダミーボタンを押した時の処理
     =================================================*/
     $('#btn').click(function() {
         $('input[type="file"]').click(); // ダミーボタンとinput[type="file"]を連動
     });

     $('input[type="file"]').change(function(e){
         var files = e.target.files;
         handleFileSelect(files);
     });
 });

 function handleFileSelect(files) {

     for (var i = 0, f; f = files[i]; i++) {

         if (!f.type.match('image.*')) { continue; }

         var reader = new FileReader();
         reader.onload = (function(theFile) {
             return function(e) {
                 // Render thumbnail.
                 var span = document.createElement('span');
                 span.innerHTML = ['<img class="thumb" src="', e.target.result,
                                   '" title="', escape(theFile.name), '"/>'].join('');
                 document.getElementById('list').insertBefore(span, null);
             };
         })(f);

         // Read in the image file as a data URL.
         reader.readAsDataURL(f);
     }

     uploadFiles(files);
 }

 function uploadFiles(files) {
     var fd = new FormData();
     var filesLength = files.length;

     // ファイル情報を追加
     for (var i = 0; i < filesLength; i++) {
         fd.append("files[]", files[i]);
     }

     $.ajax({
         url: '/products',
         type: 'POST',
         data: fd,
         dataType: "html",
         processData: false,
         contentType: false,
         success: function(data) {
             console.log('ファイルがアップロードされました。');
         },
         error:function() {
             console.log('error');
         }
     });
 }
</script>